apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T03:29:48Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7261"
  uid: e3a36e5d-3723-4e48-b9a9-0dbe72a2be05
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.169.239
  clusterIPs:
  - 10.110.169.239
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32251
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}